# Generated by Django 5.0.6 on 2024-06-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_alter_producto_fecha_bencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_bencimiento',
            new_name='fecha_vencimiento',
        ),
    ]
